// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Cargo.DataAccess.Concrete;

#nullable disable

namespace Shop.Cargo.DataAccess.Migrations
{
    [DbContext(typeof(CargoContext))]
    [Migration("20241127000959_update_co")]
    partial class update_co
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Shop.Cargo.Entity.Concrete.CargoCompany", b =>
                {
                    b.Property<int>("CargoCompanyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoCompanyID"), 1L, 1);

                    b.Property<string>("CargoCompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CargoCompanyID");

                    b.ToTable("CargoCompanies");
                });

            modelBuilder.Entity("Shop.Cargo.Entity.Concrete.CargoCustomer", b =>
                {
                    b.Property<int>("CargoCustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoCustomerID"), 1L, 1);

                    b.Property<string>("CargoCustomerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoCustomerCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoCustomerDistrict")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoCustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoCustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoCustomerPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoCustomerSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CargoCustomerID");

                    b.ToTable("CargoCustomers");
                });

            modelBuilder.Entity("Shop.Cargo.Entity.Concrete.CargoDetail", b =>
                {
                    b.Property<int>("CargoDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoDetailID"), 1L, 1);

                    b.Property<int>("CargoCompanyID")
                        .HasColumnType("int");

                    b.Property<int>("CargoCustomerID")
                        .HasColumnType("int");

                    b.Property<string>("CargoDetailReceiverCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoDetailSenderCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CargoOperationID")
                        .HasColumnType("int");

                    b.Property<int>("OrderingID")
                        .HasColumnType("int");

                    b.HasKey("CargoDetailID");

                    b.HasIndex("CargoCompanyID");

                    b.HasIndex("CargoCustomerID");

                    b.HasIndex("CargoOperationID");

                    b.ToTable("CargoDetails");
                });

            modelBuilder.Entity("Shop.Cargo.Entity.Concrete.CargoOperation", b =>
                {
                    b.Property<int>("CargoOperationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoOperationID"), 1L, 1);

                    b.Property<string>("CargoOperationBarcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CargoOperationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CargoOperationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CargoStepFive")
                        .HasColumnType("bit");

                    b.Property<bool>("CargoStepFour")
                        .HasColumnType("bit");

                    b.Property<bool>("CargoStepOne")
                        .HasColumnType("bit");

                    b.Property<bool>("CargoStepThree")
                        .HasColumnType("bit");

                    b.Property<bool>("CargoStepTwo")
                        .HasColumnType("bit");

                    b.HasKey("CargoOperationID");

                    b.ToTable("CargoOperations");
                });

            modelBuilder.Entity("Shop.Cargo.Entity.Concrete.CargoDetail", b =>
                {
                    b.HasOne("Shop.Cargo.Entity.Concrete.CargoCompany", "CargoCompany")
                        .WithMany()
                        .HasForeignKey("CargoCompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Cargo.Entity.Concrete.CargoCustomer", "CargoCustomer")
                        .WithMany()
                        .HasForeignKey("CargoCustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shop.Cargo.Entity.Concrete.CargoOperation", "CargoOperation")
                        .WithMany()
                        .HasForeignKey("CargoOperationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoCompany");

                    b.Navigation("CargoCustomer");

                    b.Navigation("CargoOperation");
                });
#pragma warning restore 612, 618
        }
    }
}
